### ISSUE TITLE
ToDo Reminder

### ISSUE THREAD

**Issue by jlorek** [jlorek/flexHttpd#3]
- [x] Add Custom HTTP Response Header
- [x] Send No-Caching Header
- [x] Allow Custom Content-Type
- [x] Remove Debug Output
- [x] Remove unused Code
- [ ] Add Stop Server Method
- [x] Add Post/Put/Delete Handlers
- [x] Add Url Parameters with curly syntax
